---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:

  - name: Delete R80.30 Gateway 
    vmware_guest:
      hostname: 10.2.0.17
      username: administrator@vsphere.local
      password: mysecretpasswd
      name: "{{ hostname }}"
      state: absent
      force: yes
      validate_certs: no


